name: Daily Car Sync

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync-cars:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the scripts
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          python scripts/doberavto_car_sync.py
          python scripts/autolina_scraper.py
          python scripts/autobid_scraper.py
          python scripts/avtonet_scraper.py
          python scripts/data_cleanup.py
